"""Vietnamese copy for the browser edition. The Japanese source stays authoritative."""

BODY = {
    'Lyric Motion は JIZURA（MIT ライセンス）をもとに開発しています。': 'Lyric Motion được phát triển dựa trên mã nguồn mở JIZURA (giấy phép MIT).',
    '<button id="btnAddFont">追加</button>': '<button id="btnAddFont">Thêm</button>',
    '曲名': 'Tên bài hát',
    '自動': 'Tự động',
    '曲名（タイトルカード・HUDに表示）': 'Tên bài hát (hiện trên thẻ tiêu đề và HUD)',
    'アーティスト': 'Nghệ sĩ',
    '表示モード': 'Chế độ hiển thị',
    'おまかせボタン中心のシンプルな画面': 'Giao diện gọn, tập trung vào nút tạo tự động',
    'すべての設定を表示': 'Hiện tất cả cài đặt',
    '保存したプロジェクト(.json)を開く': 'Mở dự án đã lưu (.json)',
    'プロジェクトを .json で保存': 'Lưu dự án dạng .json',
    'After Effects パネル用の構成データを書き出す': 'Xuất dữ liệu dự án cho panel After Effects',
    '出力物の権利とライセンス': 'Quyền và giấy phép với sản phẩm xuất ra',
    '歌詞とタイミング': 'Lời bài hát và thời gian',
    'スタイルと書き出し': 'Phong cách và xuất',
    '歌詞（1行 = 1フレーズ）': 'Lời bài hát (mỗi dòng một câu)',
    '1行が1フレーズ。空行は少し間を空けます': 'Mỗi dòng là một câu. Dòng trống sẽ thêm một khoảng nghỉ ngắn.',
    '夜明けの色を/覚えてる': 'Anh vẫn nhớ/màu bình minh',
    'でカットの切れ目を指定': 'đánh dấu điểm cắt cảnh',
    '… 強調（大きく・インパクト寄りの演出）': '… nhấn mạnh (chữ to hơn, hiệu ứng mạnh hơn)',
    '… フラッシュと揺れを入れる': '… thêm nháy sáng và rung',
    '… 注釈レイアウトの小さな文字': '… chữ nhỏ trong bố cục chú thích',
    '… LRC のタイムスタンプをそのまま使用': '… dùng mốc thời gian LRC',
    'で始まる行 … コメント（無視）': 'ở đầu dòng … ghi chú (bỏ qua)',
    '行末の': 'Cuối dòng có',
    '透明': 'trong suốt',
    '歌詞|ruby or note': 'lời|phiên âm hoặc ghi chú',
    '歌詞': 'Lời bài hát',
    '曲とタイミング': 'Nhạc và thời gian',
    '曲なし（読み込むと拍を検出してカットを合わせます）': 'Chưa có nhạc. Nhập bài hát để dò nhịp và khớp cảnh.',
    'mp3 / wav / m4a など': 'MP3, WAV, M4A và định dạng khác',
    '曲を読み込む': 'Nhập nhạc',
    '曲を再生しながら各行の頭でタップ': 'Chạm vào đầu mỗi dòng trong khi phát nhạc',
    'タップで同期': 'Chạm để đồng bộ',
    '開始(秒)': 'Bắt đầu (giây)',
    '行の長さ': 'Độ dài dòng',
    '拍にスナップ': 'Bắt theo nhịp',
    '手動タイミングを消す': 'Xóa thời gian thủ công',
    '曲に合わせて、各行が始まる瞬間に': 'Nhấn',
    'かボタンを押してください。': 'hoặc nút bấm khi mỗi dòng bắt đầu.',
    '次:': 'Tiếp:',
    '終了する': 'Kết thúc',
    '行とカット': 'Dòng và cảnh',
    '再生位置': 'Vị trí phát',
    'タイムライン（クリックで移動）': 'Dòng thời gian (bấm để tua)',
    '前の案に戻る': 'Quay lại phương án trước',
    '次の案へ進む': 'Sang phương án tiếp',
    '設定はそのままで構成だけ再抽選（ロックした行は維持）': 'Xáo lại bố cục, giữ nguyên các dòng đã khóa',
    'スタイル・雰囲気・演出・配色をまるごとランダムに（キー R）': 'Tạo ngẫu nhiên phong cách, không khí, hiệu ứng và màu (R)',
    '押すたびに、スタイル・雰囲気・動き・配色・構成がまるごと変わります。キーボードの': 'Mỗi lần bấm sẽ đổi phong cách, không khí, chuyển động, màu sắc và bố cục. Hoặc nhấn phím',
    'でも実行できます。': 'để làm tương tự.',
    '最初の公開版のあとに追加した約350の演出・配色セット12・書体6も、おまかせやシャッフルの候補にします（オフのときは最初の公開版の演出だけ）': 'Thêm khoảng 350 hiệu ứng, 12 phong cách và 6 font vào lựa chọn ngẫu nhiên. Khi tắt chỉ dùng bộ gốc.',
    '提灯・はがき・障子・扇・家紋・青海波・桜の花びらなどの和風グラフィック。オフにすると、おまかせやシャッフルで選ばれません': 'Thêm họa tiết Nhật như đèn lồng, bưu thiếp, cửa shoji, quạt, gia huy, sóng biển và cánh hoa anh đào vào lựa chọn ngẫu nhiên.',
    '「追加」印の手法・スタイル・書体。オフのときは、おまかせやシャッフルで最初の公開版の演出だけを使います': 'Thêm kỹ thuật, phong cách và font gắn nhãn Mới vào lựa chọn tự động.',
    '「和」印の手法とスタイル。オフにすると、おまかせやシャッフルでは選ばれません（追加分の判定のあとに適用。行ごとに手動で指定した場合は使えます）': 'Thêm kỹ thuật và phong cách gắn nhãn Nhật vào lựa chọn tự động. Vẫn có thể chọn thủ công.',
    '追加分の演出も使う': 'Dùng hiệu ứng mới',
    '和風の演出も使う': 'Dùng họa tiết Nhật',
    'スタイルだけ別のものに': 'Chỉ đổi phong cách',
    'アクセント・ズレ色A/Bをランダムに': 'Tạo ngẫu nhiên màu nhấn và màu lệch',
    '動き・グリッチ・使う手法の雰囲気だけ': 'Đổi không khí chuyển động, glitch và kỹ thuật',
    'レイアウトと動きの組み合わせだけ': 'Chỉ đổi bố cục và chuyển động',
    '画面比': 'Tỉ lệ khung hình',
    '解像度': 'Độ phân giải',
    '画質': 'Chất lượng',
    '通常（スタイルの背景）': 'Nền của phong cách',
    'グリーンバック（合成用）': 'Phông xanh (để ghép)',
    'ブラックバック（合成用）': 'Phông đen (để ghép)',
    'MP4 を書き出す': 'Xuất MP4',
    '書き出した動画の権利について': 'Quyền với video đã xuất',
    'フォントの役割': 'Vai trò font',
    'PCのフォント名（例: 游明朝）': 'Tên font đã cài (vd: Arial)',
    'フォントファイル（.ttf/.otf）': 'Tệp font (.ttf/.otf)',
    'アクセント・ズレ色': 'Màu nhấn và màu lệch',
    '全シーンに適用。背景に合わせて明るさを自動調整します': 'Áp dụng cho mọi cảnh. Độ sáng tự điều chỉnh theo nền.',
    '自分の色で上書き': 'Dùng màu tùy chỉnh',
    'ランダムに配色': 'Bảng màu ngẫu nhiên',
    '背景・文字色': 'Màu nền và chữ',
    'メインの背景と文字を自分の色にする': 'Dùng màu nền và màu chữ tùy chỉnh',
    '動きを何枚/秒で描くか（出力fpsとは別）': 'Số hình vẽ chuyển động mỗi giây (khác với fps xuất)',
    'フル（出力fpsのまま）': 'Đầy đủ (theo fps xuất)',
    '2コマ打ち（12枚/秒）': 'Nhịp 2 (12 hình/giây)',
    '3コマ打ち（8枚/秒）': 'Nhịp 3 (8 hình/giây)',
    'スタイル次第': 'Tự động (theo phong cách)',
    '常に表示': 'Luôn hiện',
    '表示しない': 'Ẩn',
    '同じシードなら同じ構成になります。行ごとの「再抽選」「ロック」は左の行リストから。': 'Cùng một seed sẽ cho cùng một bố cục. Tạo lại hoặc khóa từng dòng trong danh sách bên trái.',
    '手法を名前で絞り込み': 'Lọc kỹ thuật theo tên',
    'グリーンバック／ブラックバックにすると、白い文字と演出だけを単色の背景の上に描きます（背景の模様・紙の質感・粒子・周辺減光は入りません）。プレビューにもそのまま反映されます。グリーンバックは動画編集ソフトのクロマキーで、ブラックバックは「スクリーン」合成や輝度キーで抜いて、別の映像の上に重ねられます。': 'Phông xanh và phông đen chỉ vẽ chữ trắng và hiệu ứng trên nền một màu, không có họa tiết nền, vân giấy, hạt hay làm tối viền. Bản xem trước hiển thị đúng như khi xuất. Dùng chroma key cho phông xanh, hoặc chế độ hòa trộn Screen / luma key cho phông đen để ghép lên video khác.',
    '曲を動画に含める': 'Kèm nhạc vào video',
    '連番PNG（ZIP）': 'Chuỗi ảnh PNG (ZIP)',
    '透過PNG（ZIP・背景なし）': 'PNG trong suốt (ZIP)',
    '書き出した動画・画像の権利とライセンスについて': 'Quyền và giấy phép với video và hình ảnh đã xuất',
    '書き出しはこのブラウザの中で行われます（Chrome / Edge 推奨）。': 'Việc xuất diễn ra ngay trong trình duyệt (nên dùng Chrome hoặc Edge).',
    'このツールで作った': 'Quyền đối với ',
    '動画や画像（出力物）の権利は、作った人': 'video và hình ảnh bạn tạo',
    'に帰属します。': ' thuộc về bạn.',
    '※ 使った歌詞や曲の権利は、それぞれの権利者に帰属します。': 'Lời bài hát và nhạc vẫn thuộc quyền của chủ sở hữu tương ứng.',
    'ツール本体は': 'Công cụ được phát hành theo giấy phép',
    'ライセンス': 'License',
    'で公開しています。詳細なライセンスはこちら：': '. Xem giấy phép tại:',
    '入力した歌詞や曲は、このブラウザの中だけで処理され、サーバーには送信されません。': 'Lời bài hát và nhạc của bạn chỉ được xử lý trong trình duyệt này, không gửi lên máy chủ.',
    '使用しているオープンソース': 'Phần mềm mã nguồn mở',
    'MP4 書き出し：': 'Xuất MP4: ',
    'フォント：': 'Font: ',
    '配布の各書体': 'các font chữ',
    '閉じる': 'Đóng',
    'かんたん': 'Đơn giản',
    '詳細': 'Nâng cao',
    '開く': 'Mở',
    '保存': 'Lưu',
    'AE用に書き出し': 'Xuất cho AE',
    '利用について': 'Giới thiệu / quyền',
    '記法': 'Cú pháp',
    'プレビュー': 'Xem trước',
    '再生': 'Phát',
    'ループ': 'Lặp',
    '前の案': 'Trước',
    '次の案': 'Tiếp',
    'シャッフル': 'Xáo trộn',
    'おまかせで作る': 'Tạo phương án',
    'おまかせ': 'Tạo ngẫu nhiên',
    'いまの案': 'Phương án hiện tại',
    'ここだけ変える': 'Đổi một thứ',
    'スタイル': 'Phong cách',
    '配色': 'Bảng màu',
    '雰囲気': 'Không khí',
    '構成': 'Bố cục',
    '書き出し': 'Xuất',
    '縦': 'dọc',
    '背景': 'Nền',
    '追加': 'Mới',
    '和': 'Nhật',
    '演出': 'Hiệu ứng',
    '手法': 'Kỹ thuật',
    'コマ打ち': 'Nhịp khung hình',
    'フラッシュ': 'Nháy sáng',
    'シード': 'Seed',
    '新しいシード': 'Seed mới',
    '標準': 'Tiêu chuẩn',
    '最高': 'Tối đa',
    '高': 'Cao',
    '中止': 'Hủy',
}

UI = {
    '${S.plan.cuts.length}カット': '${S.plan.cuts.length} cảnh',
    '${i + 1}行目の開始秒': 'Thời điểm bắt đầu dòng ${i + 1} (giây)',
    'スタイル': 'Phong cách',
    '雰囲気': 'Không khí',
    '配色': 'Bảng màu',
    '構成': 'Bố cục',
    '演出': 'Hiệu ứng',
    '種': ' loại',
    'のフォント': ' (font)',
    'で書き出します（': '(',
    '）。': '). ',
    '最初の公開版のあとに追加': 'Thêm sau bản phát hành đầu',
    '和風の演出': 'Họa tiết Nhật',
    'フォントを読み込み中…': 'Đang tải font…',
    '一時停止': 'Tạm dừng',
    '再生': 'Phát',
    'この位置にカットはありません': 'Không có cảnh ở vị trí này',
    'スタイルの既定': 'Mặc định của phong cách',
    '見出し書体': 'Font tiêu đề',
    '見出し': 'Tiêu đề',
    '明朝枠': 'Khung chữ có chân',
    '小さな文字': 'Chữ nhỏ',
    '背景の切替': 'Đổi nền',
    '動きの強さ': 'Độ mạnh chuyển động',
    'カットの細かさ': 'Mật độ cảnh',
    '装飾の量': 'Lượng trang trí',
    '文字の加工': 'Xử lý chữ',
    '画面効果': 'Hiệu ứng màn hình',
    'カット間のつなぎ': 'Chuyển cảnh',
    'レイアウト': 'Bố cục',
    '登場': 'Xuất hiện',
    '保持': 'Giữ',
    '退場': 'Biến mất',
    '装飾': 'Trang trí',
    '加工': 'Xử lý',
    'カメラ': 'Máy quay',
    'つなぎ': 'Chuyển cảnh',
    '色ズレ': 'Lệch màu',
    'ズレ色A': 'Màu lệch A',
    'ズレ色B': 'Màu lệch B',
    'アクセント': 'Màu nhấn',
    '文字': 'Chữ',
    '補助': 'Phụ',
    '背景': 'Nền',
    'グリッチ': 'Glitch',
    '質感': 'Chất liệu',
    'この行の構成をロック': 'Khóa dòng này',
    'この行を再抽選': 'Tạo lại dòng này',
    'レイアウト指定': 'Chọn bố cục',
    '開始（秒）': 'Bắt đầu (giây)',
    '・手動': ' · thủ công',
    '・自動': ' · tự động',
    '行目の開始秒': ' – thời điểm bắt đầu (giây)',
    '行 / ': ' dòng / ',
    'カット': 'cảnh',
    '行': 'dòng ',
    '自動': 'Tự động',
    'なし': 'Không',
    'カスタム': 'Tùy chỉnh',
    'ランダム': 'Ngẫu nhiên',
    '案目': 'phương án',
    'おまかせ：': 'Ngẫu nhiên: ',
    '配色：アクセント・ズレ色A/Bを変更': 'Bảng màu: đã đổi màu nhấn và màu lệch',
    '構成：レイアウトと動きを再抽選': 'Bố cục: đã tạo lại bố cục và chuyển động',
    ' 種': ' loại',
    '・': ' · ',
    'すべてON': 'Bật tất cả',
    'すべてOFF': 'Tắt tất cả',
    '反転': 'Đảo ngược',
    '（追加分がオフのため、おまかせでは選ばれません）': ' (hiệu ứng mới đang tắt cho lựa chọn tự động)',
    '（和風の演出がオフのため、おまかせでは選ばれません）': ' (họa tiết Nhật đang tắt cho lựa chọn tự động)',
    '（追加分がオフのため、自動では選ばれません）': ' (hiệu ứng mới đang tắt cho lựa chọn tự động)',
    '（和風の演出がオフのため、自動では選ばれません）': ' (họa tiết Nhật đang tắt cho lựa chọn tự động)',
    'グリーンバック': 'Phông xanh',
    'ブラックバック': 'Phông đen',
    '白い文字と演出だけ': 'chỉ chữ trắng và hiệu ứng',
    '通常（スタイルの配色）': 'Màu của phong cách',
    'このブラウザは MP4 書き出しに対応していません（Chrome / Edge 推奨）': 'Trình duyệt này không hỗ trợ xuất MP4 (nên dùng Chrome hoặc Edge)',
    'このブラウザでは ': 'Trình duyệt này xuất bằng ',
    '書き出し中はタブを開いたままにしてください。': 'Hãy giữ tab này mở trong lúc xuất.',
    'このブラウザは動画エンコード（WebCodecs）に対応していません。Chrome / Edge の最新版で開くか、連番PNGを使ってください。': 'Trình duyệt này không hỗ trợ mã hóa video (WebCodecs). Hãy dùng Chrome hoặc Edge bản mới nhất, hoặc xuất chuỗi ảnh PNG.',
    '準備中…': 'Đang chuẩn bị…',
    '完成 ': 'Xong: ',
    '秒': 's',
    '（保存はキャンセルされました）': ' (đã hủy lưu)',
    'エラー: ': 'Lỗi: ',
    '追加分の演出：使わない（最初の公開版の演出だけ）': 'Hiệu ứng mới: tắt (chỉ dùng bộ gốc)',
    '追加分の演出：使う': 'Hiệu ứng mới: bật',
    '和風の演出：使わない（おまかせ・シャッフルで選ばれません）': 'Họa tiết Nhật: tắt khi tạo ngẫu nhiên',
    '和風の演出：使う': 'Họa tiết Nhật: bật',
    'フォントを読み込めませんでした': 'Không tải được font',
    'プロジェクトを読み込めませんでした': 'Không mở được dự án',
    '解析中…': 'Đang phân tích nhạc…',
    '読み込めませんでした: ': 'Không tải được: ',
    '約': 'khoảng ',
    '（PC）': ' (đã cài)',
    '字面': 'Chữ',
    '追加': 'Mới',
    '和': 'Nhật',
}

EXPORT = {
    'このブラウザは動画エンコード（WebCodecs）に対応していません。Chrome か Edge の最新版で開いてください。': 'Trình duyệt này không hỗ trợ mã hóa video (WebCodecs). Hãy mở bằng Chrome hoặc Edge bản mới nhất.',
    'キャンセルしました': 'Đã hủy',
    'フレーム ': 'Khung hình ',
    '音声をエンコード中': 'Đang mã hóa âm thanh',
    '完了': 'Xong',
}
